Repository NVIDIA/numba-cuda, pull requests merged in 2024-08, with the labels that each got.

#34 Fix name of array used in pseudocode to explain how atomic.dec works
  numba_cuda/numba/cuda/stubs.py
Labels: 3 - Ready for Review

#8 let `opt` respect `config.OPT`, also change its default value to `None`
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/simulator/api.py
  numba_cuda/numba/cuda/tests/cudapy/test_compiler.py
  numba_cuda/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
  numba_cuda/numba/cuda/tests/cudapy/test_exception.py
  numba_cuda/numba/cuda/tests/cudapy/test_fastmath.py
  numba_cuda/numba/cuda/tests/cudapy/test_userexc.py
  numba_cuda/numba/cuda/tests/cudapy/test_warning.py
Labels: 4 - Waiting on author

#14 Add printing support for `Dim3`s.
  numba_cuda/numba/cuda/printimpl.py
  numba_cuda/numba/cuda/tests/cudapy/test_print.py
Labels: 5 - Ready to merge

#41 Docs CI improvements
  .github/workflows/conda-python-build.yaml
  .github/workflows/docs-build.yaml
  .github/workflows/publish.yaml
  .github/workflows/wheels-build.yaml
  numba_cuda/VERSION
Labels: 2 - In Progress
