Repository NVIDIA/numba-cuda, pull requests merged in 2025-04, with the labels that each got.

#150 Add Python 3.13, and update shared-workflows.
  .github/actions/compute-matrix/action.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/docs-build.yaml
  .github/workflows/pr.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
  pyproject.toml
Labels: 4 - Waiting on reviewer

#187 Test CUDA 12.8.
  .github/actions/compute-matrix/action.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-test.yaml
  numba_cuda/numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
Labels: 4 - Waiting on author

#196 Report NVRTC builtin operation failures to the user
  numba_cuda/numba/cuda/cudadrv/error.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
Labels: 2 - In Progress

#223 Restore PR #185 (Stop Certain Driver API Discovery for "v2")
  numba_cuda/numba/cuda/cudadrv/driver.py
Labels: 3 - Ready for Review

#155 Locate nvvm, libdevice, nvrtc, and cudart from nvidia-*-cu12 wheels
  .github/workflows/pr.yaml
  ci/test_conda.sh
  ci/test_wheel_deps_wheels.sh
  numba_cuda/numba/cuda/cuda_paths.py
  numba_cuda/numba/cuda/cudadrv/libs.py
Labels: 4 - Waiting on reviewer

#229 Bump version to 0.9.0
  numba_cuda/VERSION
Labels: 4 - Waiting on CI

#193 Feature: cuda specific make_attribute_wrapper
  numba_cuda/numba/cuda/extending.py
  numba_cuda/numba/cuda/tests/cudapy/extensions_usecases.py
  numba_cuda/numba/cuda/tests/cudapy/test_extending.py
  numba_cuda/numba/cuda/vector_types.py
Labels: 5 - Ready to merge
