Repository NVIDIA/numba-cuda, pull requests merged in 2025-09, with the labels that each got.

#441 [Refactor][NFC] Vendor-in tracing module for future CUDA-specific changes
  numba_cuda/numba/cuda/core/compiler.py
  numba_cuda/numba/cuda/core/compiler_machinery.py
  numba_cuda/numba/cuda/core/tracing.py
  numba_cuda/numba/cuda/tests/test_tracing.py
Labels: 5 - Ready to merge

#442 Vendor in the typeinfer module
  numba_cuda/numba/cuda/core/typed_passes.py
  numba_cuda/numba/cuda/core/typeinfer.py
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/tests/cudapy/test_typeinfer.py
Labels: 4 - Waiting on CI

#445 Vendor the base module for CUDA-specific refactoring
  numba_cuda/numba/cuda/core/base.py
  numba_cuda/numba/cuda/target.py
Labels: 3 - Ready for Review

#449 [Refactor][NFC] Vendor-in external_compiler_works from pycc for future CUDA-specific changes
  numba_cuda/numba/cuda/tests/support.py
Labels: 4 - Waiting on author

#444 Vendor in the transforms module
  numba_cuda/numba/cuda/core/compiler_machinery.py
  numba_cuda/numba/cuda/core/postproc.py
  numba_cuda/numba/cuda/core/transforms.py
  numba_cuda/numba/cuda/core/untyped_passes.py
Labels: 3 - Ready for Review

#463 Vendor the annotations module for CUDA-specific refactoring
  numba_cuda/numba/cuda/core/annotations/__init__.py
  numba_cuda/numba/cuda/core/annotations/template.html
  numba_cuda/numba/cuda/core/annotations/type_annotations.py
  numba_cuda/numba/cuda/core/typed_passes.py
  numba_cuda/numba/cuda/tests/cudapy/test_copy_propagate.py
Labels: 4 - Waiting on CI

#429 Avoid Using Device Compute Capability for Linker Class
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/tests/cudadrv/test_linker.py
Labels: 4 - Waiting on author

#456 Vendor in targetconfig, event, funcdesc, descriptors for CUDA-specific changes
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/compiler.py
  numba_cuda/numba/cuda/core/compiler_machinery.py
  numba_cuda/numba/cuda/core/event.py
  numba_cuda/numba/cuda/core/funcdesc.py
  numba_cuda/numba/cuda/core/targetconfig.py
  numba_cuda/numba/cuda/core/typed_passes.py
  numba_cuda/numba/cuda/descriptor.py
  numba_cuda/numba/cuda/flags.py
  numba_cuda/numba/cuda/lowering.py
  numba_cuda/numba/cuda/mathimpl.py
  numba_cuda/numba/cuda/nvvmutils.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/typing/templates.py
Labels: 5 - Ready to merge

#476 Vendor in optional, boxing for CUDA-specific changes, fix dangling imports
  numba_cuda/numba/cuda/core/base.py
  numba_cuda/numba/cuda/core/boxing.py
  numba_cuda/numba/cuda/core/callconv.py
  numba_cuda/numba/cuda/core/compiler.py
  numba_cuda/numba/cuda/core/cpu.py
  numba_cuda/numba/cuda/core/inline_closurecall.py
  numba_cuda/numba/cuda/core/optional.py
  numba_cuda/numba/cuda/core/options.py
  numba_cuda/numba/cuda/core/pythonapi.py
  numba_cuda/numba/cuda/core/rewrites/registry.py
  numba_cuda/numba/cuda/core/rewrites/static_raise.py
  numba_cuda/numba/cuda/core/transforms.py
  numba_cuda/numba/cuda/core/typeinfer.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/nocuda/test_import.py
Labels: 5 - Ready to merge
