Repository NVIDIA/numba-cuda, pull requests merged in 2025-07, with the labels that each got.

#315 Bump version to 0.16.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#314 Fix nvrtc resolution when CUDA_HOME env is set
  numba_cuda/numba/cuda/cuda_paths.py
Labels: 4 - Waiting on reviewer

#321 Add deadlock warnings to Stream.add_callback and Stream.async_done docstrings
  numba_cuda/numba/cuda/cudadrv/driver.py
Labels: 5 - Ready to merge

#333 [REVIEW][NFC] Vendor in the MinimalCallConv used by CUDACallConv to allow for future CUDA-specific refactoring and changes
  numba_cuda/numba/cuda/core/callconv.py
  numba_cuda/numba/cuda/target.py
Labels: 5 - Ready to merge

#332 [NFC] Vendor in DIBuilder used by CUDADIBuilder
  numba_cuda/numba/cuda/debuginfo.py
Labels: 5 - Ready to merge

#326 Allow Inspection of Link-Time Optimized PTX
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/testing.py
  numba_cuda/numba/cuda/tests/cudapy/test_inspect.py
Labels: 4 - Waiting on CI

#342 [RFC,TESTING] Add filecheck test infrastructure
  ci/test_conda.sh
  ci/test_conda_ctypes_binding.sh
  ci/test_simulator.sh
  numba_cuda/numba/cuda/simulator/__init__.py
  numba_cuda/numba/cuda/simulator/dispatcher.py
  numba_cuda/numba/cuda/testing.py
  numba_cuda/numba/cuda/tests/cudapy/test_inspect.py
  pyproject.toml
Labels: 5 - Ready to merge

#340 [REVIEW][NFC] Vendor in the utils and cgutils to allow for future CUDA-specific refactoring and changes
  numba_cuda/numba/cuda/cgutils.py
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/callconv.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/cudadrv/nvvm.py
  numba_cuda/numba/cuda/cudaimpl.py
  numba_cuda/numba/cuda/debuginfo.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/extending.py
  numba_cuda/numba/cuda/intrinsics.py
  numba_cuda/numba/cuda/libdeviceimpl.py
  numba_cuda/numba/cuda/mathimpl.py
  numba_cuda/numba/cuda/nvvmutils.py
  numba_cuda/numba/cuda/printimpl.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/cudapy/extensions_usecases.py
  numba_cuda/numba/cuda/tests/cudapy/test_extending.py
  numba_cuda/numba/cuda/tests/nocuda/test_nvvm.py
  numba_cuda/numba/cuda/utils.py
  numba_cuda/numba/cuda/vector_types.py
Labels: 4 - Waiting on reviewer

#327 Vendor in Codegen and CodeLibrary for CUDA-specific customization
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/core/codegen.py
Labels: 3 - Ready for Review

#329 Vendor in BaseNativeLowering and BaseLower for CUDA-specific customizations
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/typed_passes.py
  numba_cuda/numba/cuda/lowering.py
  pyproject.toml
Labels: 4 - Waiting on reviewer

#359 Vendor in usecases used in testing
  numba_cuda/numba/cuda/tests/complex_usecases.py
  numba_cuda/numba/cuda/tests/cudapy/test_complex.py
  numba_cuda/numba/cuda/tests/cudapy/test_enums.py
  numba_cuda/numba/cuda/tests/enum_usecases.py
Labels: 5 - Ready to merge

#349 [REVIEW][NFC] Vendor in serialize to allow for future CUDA-specific refactoring and changes
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/serialize.py
  numba_cuda/numba/cuda/tests/core/serialize_usecases.py
  numba_cuda/numba/cuda/tests/core/test_serialize.py
Labels: 4 - Waiting on CI

#365 Bump version to 0.18.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#357 Remove remaining references/dependencies on `pynvjitlink`
  ci/test_wheel_deps_wheels.sh
  docs/source/reference/envvars.rst
  docs/source/user/minor_version_compatibility.rst
  numba_cuda/numba/cuda/__init__.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/simulator/cudadrv/driver.py
  numba_cuda/numba/cuda/tests/cudapy/test_errors.py
  numba_cuda/numba/cuda/tests/test_binary_generation/Makefile
  pyproject.toml
Labels: 4 - Waiting on reviewer

#362 [Refactor][NFC] Vendor in Itanium Mangler for future CUDA-specific changes
  numba_cuda/numba/cuda/itanium_mangler.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/core/test_itanium_mangler.py
Labels: 4 - Waiting on author
