Repository NVIDIA/numba-cuda, pull requests merged in 2025-08, with the labels that each got.

#363 [Refactor][NFC] Vendor in TestCase and other testing helpers for CUDA-specific changes
  numba_cuda/numba/cuda/testing.py
  numba_cuda/numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba_cuda/numba/cuda/tests/cudadrv/test_deallocations.py
  numba_cuda/numba/cuda/tests/cudadrv/test_detect.py
  numba_cuda/numba/cuda/tests/cudadrv/test_emm_plugins.py
  numba_cuda/numba/cuda/tests/cudadrv/test_linker.py
  numba_cuda/numba/cuda/tests/cudadrv/test_managed_alloc.py
  numba_cuda/numba/cuda/tests/cudadrv/test_mvc.py
  numba_cuda/numba/cuda/tests/cudadrv/test_ptds.py
  numba_cuda/numba/cuda/tests/cudapy/test_caching.py
  numba_cuda/numba/cuda/tests/cudapy/test_cffi.py
  numba_cuda/numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba_cuda/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
  numba_cuda/numba/cuda/tests/cudapy/test_debug.py
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo.py
  numba_cuda/numba/cuda/tests/cudapy/test_device_func.py
  numba_cuda/numba/cuda/tests/cudapy/test_gufunc.py
  numba_cuda/numba/cuda/tests/cudapy/test_ipc.py
  numba_cuda/numba/cuda/tests/cudapy/test_lineinfo.py
  numba_cuda/numba/cuda/tests/cudapy/test_ufuncs.py
  numba_cuda/numba/cuda/tests/cudapy/test_warning.py
  numba_cuda/numba/cuda/tests/doc_examples/test_cpointer.py
  numba_cuda/numba/cuda/tests/doc_examples/test_cpu_gpu_compat.py
  numba_cuda/numba/cuda/tests/doc_examples/test_ffi.py
  numba_cuda/numba/cuda/tests/doc_examples/test_laplace.py
  numba_cuda/numba/cuda/tests/doc_examples/test_matmul.py
  numba_cuda/numba/cuda/tests/doc_examples/test_montecarlo.py
  numba_cuda/numba/cuda/tests/doc_examples/test_reduction.py
  numba_cuda/numba/cuda/tests/doc_examples/test_sessionize.py
  numba_cuda/numba/cuda/tests/doc_examples/test_ufunc.py
  numba_cuda/numba/cuda/tests/doc_examples/test_vecadd.py
  numba_cuda/numba/cuda/tests/nocuda/test_import.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt_refct.py
  numba_cuda/numba/cuda/tests/support.py
Labels: 5 - Ready to merge

#355 Vendor in Bytecode Interpreter
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/interpreter.py
Labels: 5 - Ready to merge

#385 Fix CI for CUDA 13 drivers
  ci/matrix.yml
  ci/test_wheel_ctypes_binding.sh
  numba_cuda/numba/cuda/tests/cudadrv/test_context_stack.py
  numba_cuda/numba/cuda/tests/cudapy/test_inspect.py
Labels: 5 - Ready to merge

#381 Add locals attribute to _FunctionCompiler
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/tests/cudapy/test_compiler.py
Labels: 5 - Ready to merge

#371 Relax subclass check in vendored in typing templates
  numba_cuda/numba/cuda/typing/templates.py
Labels: 5 - Ready to merge

#377 Vendor-in IR utilities for CUDA-specific refactoring
  numba_cuda/numba/cuda/core/interpreter.py
  numba_cuda/numba/cuda/core/ir_utils.py
  numba_cuda/numba/cuda/lowering.py
  numba_cuda/numba/cuda/tests/cudapy/test_ir_utils.py
  numba_cuda/numba/cuda/typing/templates.py
Labels: 5 - Ready to merge

#345 [NFC] Document development dependencies and dependency groups
  CONTRIBUTING.md
  pyproject.toml
Labels: 4 - Waiting on reviewer

#370 Support CUDA 13, drop support for CUDA 11
  .github/workflows/pr.yaml
  ci/matrix.yml
  ci/test_conda.sh
  ci/test_wheel_deps_wheels.sh
  docs/source/reference/envvars.rst
  docs/source/user/cudapysupported.rst
  docs/source/user/installation.rst
  docs/source/user/minor_version_compatibility.rst
  numba_cuda/numba/cuda/api.py
  numba_cuda/numba/cuda/cuda_paths.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/cudadrv/libs.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
  numba_cuda/numba/cuda/cudadrv/nvvm.py
  numba_cuda/numba/cuda/cudadrv/runtime.py
  numba_cuda/numba/cuda/include/11/cuda_bf16.h
  numba_cuda/numba/cuda/include/11/cuda_bf16.hpp
  numba_cuda/numba/cuda/include/11/cuda_fp16.h
  numba_cuda/numba/cuda/include/11/cuda_fp16.hpp
  numba_cuda/numba/cuda/tests/cudadrv/test_nvrtc.py
  numba_cuda/numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
  numba_cuda/numba/cuda/tests/cudapy/test_compiler.py
  numba_cuda/numba/cuda/tests/cudapy/test_extending.py
  numba_cuda/numba/cuda/tests/test_binary_generation/Makefile
  numba_cuda/numba/cuda/tests/test_binary_generation/build.bat
  numba_cuda/numba/cuda/tests/test_binary_generation/generate_raw_ltoir.py
  pyproject.toml
Labels: 3 - Ready for Review

#387 Require `cuda-bindings` `12.9.1`
  conda/recipes/numba-cuda/meta.yaml
  pyproject.toml
Labels: 4 - Waiting on CI

#400 Bump version to 0.19.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#364 Vendor in additional debug info tests
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo.py
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo_types.py
Labels: 5 - Ready to merge

#383 Remove _helperlib dep., implement attempt_nocopy_reshape in python for CUDA-specific changes
  numba_cuda/numba/cuda/cudadrv/dummyarray.py
Labels: 4 - Waiting on reviewer

#413 Remove `MVCLinker` and straggling uses of / references to `cubinlinker`
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/testing.py
  numba_cuda/numba/cuda/tests/cudadrv/test_mvc.py
  numba_cuda/numba/cuda/tests/cudapy/test_caching.py
  numba_cuda/numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba_cuda/numba/cuda/tests/doc_examples/test_cg.py
  numba_cuda/numba/cuda/tests/doc_examples/test_laplace.py
  numba_cuda/numba/cuda/tests/doc_examples/test_sessionize.py
Labels: 5 - Ready to merge

#416 Remove costly but low-utility assertions
  numba_cuda/numba/cuda/typing/templates.py
Labels: 3 - Ready for Review

#392 Backport interpreter.py for Python 3.9
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/interpreter.py
Labels: 5 - Ready to merge

#376 Improve Bfloat16 Support in Numba-CUDA
  ci/test_conda.sh
  ci/test_conda_ctypes_binding.sh
  ci/test_simulator.sh
  configs/cuda_bf16.yml
  docs/source/reference/types.rst
  numba_cuda/numba/cuda/_internal/cuda_bf16.py
  numba_cuda/numba/cuda/bf16.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
  numba_cuda/numba/cuda/include/13/cuda_bf16.h
  numba_cuda/numba/cuda/include/13/cuda_bf16.hpp
  numba_cuda/numba/cuda/include/13/cuda_fp16.h
  numba_cuda/numba/cuda/include/13/cuda_fp16.hpp
  numba_cuda/numba/cuda/models.py
  numba_cuda/numba/cuda/printimpl.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
  numba_cuda/numba/cuda/tests/cudapy/test_print.py
  numba_cuda/numba/cuda/types.py
  pyproject.toml
Labels: 5 - Ready to merge

#421 Depend on `cccl` explicitly for `[cuXY]` wheels
  pyproject.toml
Labels: 5 - Ready to merge

#423 Bump version to 0.14.1
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#419 Vendor in the consts module for CUDA-specific refactoring
  numba_cuda/numba/cuda/core/analysis.py
  numba_cuda/numba/cuda/core/consts.py
  numba_cuda/numba/cuda/core/untyped_passes.py
Labels: 3 - Ready for Review, 5 - Ready to merge

#417 Vendor in SSA for CUDA-specific refactoring
  numba_cuda/numba/cuda/core/ssa.py
  numba_cuda/numba/cuda/core/untyped_passes.py
  numba_cuda/numba/cuda/tests/cudapy/test_ssa.py
Labels: 4 - Waiting on CI

#425 [Cleanup] Remove deadcode parfor support
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/core/compiler.py
  numba_cuda/numba/cuda/core/ir_utils.py
  numba_cuda/numba/cuda/core/typed_passes.py
  numba_cuda/numba/cuda/core/untyped_passes.py
  numba_cuda/numba/cuda/dispatcher.py
Labels: 4 - Waiting on CI

#428 Bfloat Test Expects Different PTX Based on CC
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
Labels: 4 - Waiting on reviewer

#396 Windows ci
  .github/workflows/install_gpu_driver.ps1
  .github/workflows/pr.yaml
  .github/workflows/wheel-windows-tests.yaml
  ci/get_test_binary_dir.py
  ci/test_wheel.ps1
  numba_cuda/numba/cuda/cuda_paths.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
Labels: 5 - Ready to merge

#398 Vendor in debuginfo, utils, cffi_utils, enumdecl for CUDA-specific changes
  numba_cuda/numba/cuda/cgutils.py
  numba_cuda/numba/cuda/debuginfo.py
  numba_cuda/numba/cuda/lowering.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/core/test_serialize.py
  numba_cuda/numba/cuda/tests/support.py
  numba_cuda/numba/cuda/typing/cffi_utils.py
  numba_cuda/numba/cuda/typing/enumdecl.py
  numba_cuda/numba/cuda/typing/templates.py
  numba_cuda/numba/cuda/utils.py
Labels: 5 - Ready to merge
