Repository NVIDIA/numba-cuda, pull requests merged in 2025-10, with the labels that each got.

#485 Vendor in core.registry for CUDA-specific changes
  numba_cuda/numba/cuda/core/cpu.py
  numba_cuda/numba/cuda/core/inline_closurecall.py
  numba_cuda/numba/cuda/core/ir_utils.py
  numba_cuda/numba/cuda/core/registry.py
  numba_cuda/numba/cuda/cudadrv/ndarray.py
Labels: 2 - In Progress

#484 Add `compile_all` API
  docs/source/reference/host.rst
  numba_cuda/numba/cuda/__init__.py
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/cudadrv/linkable_code.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
  numba_cuda/numba/cuda/simulator/__init__.py
  numba_cuda/numba/cuda/simulator/compiler.py
  numba_cuda/numba/cuda/tests/cudadrv/test_linkable_code.py
  numba_cuda/numba/cuda/tests/cudapy/test_compiler.py
Labels: 5 - Ready to merge

#498 Vendor in components from numba.core.runtime for CUDA-specific changes
  numba_cuda/numba/cuda/core/base.py
  numba_cuda/numba/cuda/memory_management/nrt.py
  numba_cuda/numba/cuda/memory_management/nrt_context.py
Labels: 3 - Ready for Review

#437 Ensure NUMBA can manipulate memory from CUDA graphs before the graph is launched
  numba_cuda/numba/cuda/api.py
  numba_cuda/numba/cuda/cudadrv/devicearray.py
Labels: 5 - Ready to merge

#506 Remove C extension loading hacks
  README.md
  ci/build_docs.sh
  ci/coverage_report.sh
  ci/get_test_binary_dir.py
  ci/test_conda.sh
  ci/test_conda_ctypes_binding.sh
  ci/test_simulator.sh
  ci/test_wheel.ps1
  ci/test_wheel.sh
  ci/test_wheel_ctypes_binding.sh
  ci/test_wheel_deps_wheels.sh
  numba_cuda/numba/cuda/cext/__init__.py
  numba_cuda/numba/cuda/cext/_devicearray.h
  numba_cuda/numba/cuda/cext/_dispatcher.cpp
  pyproject.toml
  testing/Makefile
  testing/build.bat
  testing/conftest.py
  testing/generate_raw_ltoir.py
  testing/nrt_extern.cu
  testing/pytest.ini
  testing/test_device_functions.cu
  testing/undefined_extern.cu
Labels: 3 - Ready for Review
