Repository NVIDIA/numba-cuda, pull requests merged in 2025-03, with the labels that each got.

#147 Move publish step out of `wheels-build.yaml`
  .github/workflows/publish.yaml
  .github/workflows/wheels-build.yaml
  ci/build_conda.sh
Labels: 3 - Ready for Review

#149 Bump version to 0.6.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#136 Emit correct kernel arguments debug metadata types when NUMBA_DUMP_LLVM is on
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo.py
Labels: 4 - Waiting on author

#158 Bump version to 0.7.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#160 Add support for default overload values
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/tests/cudapy/test_overload.py
Labels: 5 - Ready to merge

#161 Switch to real NumPy from mock NumPy
  numba_cuda/numba/cuda/tests/nrt/mock_numpy.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt_refct.py
Labels: 5 - Ready to merge

#168 Fix NRT stats for cuda python
  numba_cuda/numba/cuda/runtime/nrt.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt.py
Labels: 5 - Ready to merge
