Repository NVIDIA/numba-cuda, pull requests merged in 2025-05, with the labels that each got.

#181 Fix cuda.jit decorator inline
  docs/source/user/ufunc.rst
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/tests/cudapy/test_array_args.py
  numba_cuda/numba/cuda/tests/cudapy/test_blackscholes.py
  numba_cuda/numba/cuda/tests/cudapy/test_inline.py
  numba_cuda/numba/cuda/tests/cudapy/test_laplace.py
  numba_cuda/numba/cuda/vectorizers.py
Labels: 5 - Ready to merge

#166 Add Bfloat16 Low++ Bindings
  configs/cuda_bf16.yml
  numba_cuda/numba/cuda/cuda_bf16.py
  numba_cuda/numba/cuda/cudadrv/linkable_code.py
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
  numba_cuda/numba/cuda/include/11/cuda_bf16.h
  numba_cuda/numba/cuda/include/11/cuda_bf16.hpp
  numba_cuda/numba/cuda/include/11/cuda_fp16.h
  numba_cuda/numba/cuda/include/11/cuda_fp16.hpp
  numba_cuda/numba/cuda/include/12/cuda_bf16.h
  numba_cuda/numba/cuda/include/12/cuda_bf16.hpp
  numba_cuda/numba/cuda/include/12/cuda_fp16.h
  numba_cuda/numba/cuda/include/12/cuda_fp16.hpp
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
  numba_cuda/numba/cuda/tests/cudapy/test_enums.py
  pyproject.toml
Labels: 5 - Ready to merge

#231 Fix Invalid NVVM IR emitted when lowering shfl_sync APIs
  numba_cuda/numba/cuda/cudadecl.py
  numba_cuda/numba/cuda/cudaimpl.py
  numba_cuda/numba/cuda/device_init.py
  numba_cuda/numba/cuda/intrinsic_wrapper.py
  numba_cuda/numba/cuda/intrinsics.py
  numba_cuda/numba/cuda/stubs.py
  numba_cuda/numba/cuda/tests/cudapy/test_warp_ops.py
Labels: 5 - Ready to merge

#238 Fix package installation for wheels CI
  .github/workflows/wheels-test.yaml
  ci/test_wheel.sh
  ci/test_wheel_deps_wheels.sh
  ci/test_wheel_pynvjitlink.sh
Labels: 5 - Ready to merge

#222 Local variable debug info deduplication
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/debuginfo.py
  numba_cuda/numba/cuda/lowering.py
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo.py
Labels: 5 - Ready to merge

#143 Implement alignment support for local and shared arrays.
  numba_cuda/numba/cuda/cudadecl.py
  numba_cuda/numba/cuda/cudaimpl.py
  numba_cuda/numba/cuda/stubs.py
  numba_cuda/numba/cuda/tests/cudapy/test_array_alignment.py
Labels: 5 - Ready to merge

#241 Fixes for adding data to link
  ci/test_conda.sh
  ci/test_wheel.sh
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/cudadrv/linkable_code.py
  numba_cuda/numba/cuda/tests/cudapy/test_extending.py
  numba_cuda/numba/cuda/tests/test_binary_generation/test_device_functions.cu
Labels: 3 - Ready for Review

#167 Support consuming NRT functions from external libraries
  ci/test_wheel.sh
  ci/test_wheel_deps_wheels.sh
  ci/test_wheel_pynvjitlink.sh
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/cudadrv/linkable_code.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/runtime/nrt.cu
  numba_cuda/numba/cuda/runtime/nrt.cuh
  numba_cuda/numba/cuda/runtime/nrt.py
  numba_cuda/numba/cuda/tests/nrt/test_nrt.py
  numba_cuda/numba/cuda/tests/test_binary_generation/Makefile
  numba_cuda/numba/cuda/tests/test_binary_generation/generate_raw_ltoir.py
  numba_cuda/numba/cuda/tests/test_binary_generation/nrt_extern.cu
  numba_cuda/numba/cuda/utils.py
Labels: 4 - Waiting on reviewer

#248 Bump version to 0.10.1
  numba_cuda/VERSION
Labels: 2 - In Progress

#246 Fix inlining behaviour at the NVVM IR level
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/tests/cudapy/test_inline.py
Labels: 4 - Waiting on reviewer

#250 Bump version to 0.11.0
  numba_cuda/VERSION
Labels: 5 - Ready to merge

#249 Simplify the CI build and test matrix
  .github/actions/compute-matrix/action.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/pr.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
  ci/matrix.yml
Labels: 2 - In Progress

#244 Add Test to Use Bf16 Bindings inside Device Function
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
Labels: 5 - Ready to merge

#245 Add Bfloat16 High Level API, Documentation
  docs/source/reference/types.rst
  numba_cuda/numba/cuda/_internal/cuda_bf16.py
  numba_cuda/numba/cuda/api.py
  numba_cuda/numba/cuda/bf16.py
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16.py
  numba_cuda/numba/cuda/tests/cudapy/test_bfloat16_bindings.py
Labels: 5 - Ready to merge

#254 Allow Numba NVRTC Binding Search Additional Paths
  docs/source/reference/envvars.rst
  docs/source/user/cuda_ffi.rst
  numba_cuda/numba/cuda/cudadrv/nvrtc.py
  numba_cuda/numba/cuda/tests/data/include/add.cuh
  numba_cuda/numba/cuda/tests/doc_examples/ffi/include/mul.cuh
  numba_cuda/numba/cuda/tests/doc_examples/ffi/saxpy.cu
  numba_cuda/numba/cuda/tests/doc_examples/test_ffi.py
Labels: 5 - Ready to merge

#242 Improve debug info for kernel arguments
  numba_cuda/numba/cuda/debuginfo.py
  numba_cuda/numba/cuda/target.py
  numba_cuda/numba/cuda/tests/cudapy/test_debuginfo.py
Labels: 5 - Ready to merge

#240 Allow External Code to Use Coorperative Group
  numba_cuda/numba/cuda/cg.py
  numba_cuda/numba/cuda/codegen.py
  numba_cuda/numba/cuda/compiler.py
  numba_cuda/numba/cuda/cudadecl.py
  numba_cuda/numba/cuda/decorators.py
  numba_cuda/numba/cuda/dispatcher.py
  numba_cuda/numba/cuda/tests/cudapy/cache_usecases.py
  numba_cuda/numba/cuda/tests/cudapy/cg_cache_usecases.py
  numba_cuda/numba/cuda/tests/cudapy/test_caching.py
  numba_cuda/numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba_cuda/numba/cuda/tests/data/cta_barrier.cu
Labels: 5 - Ready to merge

#258 Bump to version 0.12.0
  numba_cuda/VERSION
Labels: 4 - Waiting on CI

#261 Fix `test_external_cooperative_func()`
  numba_cuda/numba/cuda/tests/cudapy/test_cooperative_groups.py
Labels: 5 - Ready to merge

#263 Always enable pynvjitlink if available
  docs/source/user/minor_version_compatibility.rst
  numba_cuda/numba/cuda/cudadrv/driver.py
  numba_cuda/numba/cuda/tests/cudadrv/test_nvjitlink.py
Labels: 3 - Ready for Review
